// finally will be neither be invoked in case of negative value nor in positive value as "System.exit" is used inside both "try" and "catch" blocks.

public class Example12_c
{
	void accept(int k)
	{
		if(k<=0)
		{
			throw new RuntimeException("invalid value");
		}
	}
	int disp(int k)
	{ 
		try
		{
			accept(k);
			System.exit(0);
			return 1;
		}
		catch(Exception ex)
		{
			System.exit(0);
			return 2;
		}
		finally
		{
			return 3;
		}
	}
	public static void main(String args[])
	{
		Example12_c e=new Example12_c();
		System.out.println(e.disp(5));
		//System.out.println(e.disp(-5));
	}
}
				