throwCall effect can be seen only after handling the exception.